#ifndef SHIM3_H
#define SHIM3_H

#include "shim3/a_star.h"
#include "shim3/achievements.h"
#include "shim3/audio.h"
#include "shim3/cd.h"
#include "shim3/cloud.h"
#include "shim3/cpa.h"
#include "shim3/error.h"
#include "shim3/gfx.h"
#include "shim3/gui.h"
#include "shim3/image.h"
#include "shim3/input.h"
#include "shim3/interp.h"
#include "shim3/json.h"
#include "shim3/main.h"
#include "shim3/md5.h"
#include "shim3/mml.h"
#include "shim3/mt.h"
#include "shim3/model.h"
#include "shim3/pixel_font.h"
#include "shim3/primitives.h"
#include "shim3/sample.h"
#include "shim3/shim.h"
#include "shim3/shader.h"
#include "shim3/sprite.h"
#include "shim3/tilemap.h"
#include "shim3/tokenizer.h"
#include "shim3/translation.h"
#ifdef USE_TTF
#include "shim3/ttf.h"
#endif
#include "shim3/utf8.h"
#include "shim3/util.h"
#include "shim3/vertex_cache.h"
#include "shim3/vorbis.h"
//#include "shim3/xml.h"

#endif // SHIM3_H
